const { execSync } = require('child_process');
const fs = require('fs');
const ZIP = 'C:/Users/ASUS/Desktop/乒乓对决_安装包.zip';
const list = execSync('"C:/Program Files/7-Zip/7z.exe" l "' + ZIP + '"', { encoding: 'utf8' });
console.log('ZIP 条目示例:', list.split('\n').filter((l) => /index\.html|package\.json/.test(l)).slice(0, 4).join(' | '));
const CHK = 'C:/Users/ASUS/AppData/Local/Temp/pkg_check2';
fs.rmSync(CHK, { recursive: true, force: true });
fs.mkdirSync(CHK, { recursive: true });
execSync('"C:/Program Files/7-Zip/7z.exe" e -y -o' + CHK + ' "' + ZIP + '" game/index.html game/package.json', { encoding: 'utf8' });
const idx = fs.readFileSync(CHK + '/index.html', 'utf8');
const pj = JSON.parse(fs.readFileSync(CHK + '/package.json', 'utf8'));
console.log('ZIP 内游戏: version=' + pj.version + ' | btnManualMenu=' + idx.includes('btnManualMenu') + ' | btnManualTouch 已移除=' + !idx.includes('btnManualTouch') + ' | 胶囊open数=' + (idx.match(/manual-capsule"[^>]* open>/g) || []).length);
console.log('ZIP 大小:', fs.statSync(ZIP).size);
